### ISSUE TITLE
Any plans to support dynamic columns?

### ISSUE THREAD

**Issue by depeele** [Saulis/iron-data-table#10]
I have a project where I would like to have a dynamic number of columns as determined by the data. For example, given two inter-related data sets, call them A and B, that together form a two-dimensional matrix. I'd like the header row to be taken from A, the first column from B, and the intersection from the matrix.

It seems that I need a repeated template in order to include columns 2..n but I can't seem to get it to work. In the following example, column 1 is fully rendered but columns 2..n are not.

```
<iron-data-table items="{{A}}">
  <!-- column 1 { -->
  <data-table-column>
    <template is="header">
      <div class="right" title="Add B" on-click="addB">B<i class="icon add circle"></i></div>
      <div class="left" title="Add A" on-click="addA"><i class="icon add circle"></i>A</div>
    </template>
    <template>
      <ui-A-card item="{{item}}"></ui-A-card>
    </template>
  </data-table-column>
  <!-- column 1 } -->
  <!-- columns 2..n { -->
  <template is="dom-repeat" items="{{B}}" as="bItem" index-as="bdex>
    <data-table-column>
      <template is="header">
        <ui-B-card item="{{bItem}}"></ui-B-card>
      </template>
      <template>
        <ui-AB-card item="{{ getItem(item, bItem) }}"></ui-AB-card>
      </template>
    </data-table-column>
  </template>
  <!-- columns 2..n } -->
</iron-data-table>
```

Does iron-data-table not allow repeat templates when laying out the columns??

**Comment by Saulis** [comment]
Hi there!

Pretty advanced setup you've got there :)

Dynamic columns should pretty much work when modifying the columns property with push or pop for example.

Haven't yet tried out the declarative support with dom-repeat yet, though.

Something I'd definitely consider, but I need to get back with you on that after prototyping it to see how big of an effort it would be.

**Comment by Saulis** [comment]
Did some initial prototyping, looks like I only need to add a node observer for the Light DOM and add some minor tweaks on the parent property forwarding, so this should be doable in time for the beta release.

**Comment by Saulis** [comment]
@depeele could you do me a favour and test if the version in branch `feature/dynamic-columns` works for you? 

`bower install iron-data-table#feature/dynamic-columns`

Thanks!

**Comment by depeele** [comment]
The `feature/dynamic-columns` branch seems to work for me.

Thanks for the quick response!!

Here is the code I used to test on Chrome:

`index.html`

```
<html>
 <head>
  <link rel="import" href="./dynamic-columns.html" />
 </head>
 <body unresolved>
  <ui-dynamic-columns></ui-dynamic-columns>
</html>
```

`dynamic-columns.html`

```
<link rel="import" href="./lib/iron-data-table/iron-data-table.html" />
<dom-module id="ui-dynamic-columns">
  <template>
    <iron-data-table items="{{Aitems}}">
      <!-- column 1 { -->
      <data-table-column>
        <template is="header">th</template>
        <template><div class='A-card'>{{ item.name }}</div></template>
      </data-table-column>
      <!-- column 1 } -->
      <!-- column 2..n { -->
      <template id="table-body" is="dom-repeat"
                items="{{Bitems}}"   as="bItem" index-as="bdex">
        <data-table-column>
          <template is="header">{{bItem.name}}</template>
          <template>
            <div class='A-card'>{{ getItem(bdex, index) }}</div>
          </template>
        </data-table-column>
      </template>
      <!-- column 2..n } -->
    </iron-data-table>
  </template>
</dom-module>

<script>
(function() {
    'use strict';
    let A = [
        {name:'A1'},
        {name:'A2'},
        {name:'A3'},
        {name:'A4'},
    ];
    let B = [
        {name:'B1', data:['AB1,1','AB1,2','AB1,3','AB1,4']},
        {name:'B2', data:['AB2,1','AB2,2','AB2,3','AB2,4']},
        {name:'B3', data:['AB3,1','AB3,2','AB3,3','AB3,4']},
        {name:'B4', data:['AB4,1','AB4,2','AB4,3','AB4,4']},
    ];

    Polymer({
        is: 'ui-dynamic-columns',
        properties: {
            Aitems:  Array,
            Bitems:  Array,
        },
        ready: function() {
            this.Aitems = A;
            this.Bitems = B;
        },
        getItem: function(bdex, adex) {
            let b = this.Bitems[bdex];
            return b.data[adex];
        },
    });
}());
</script>
```

**Comment by Saulis** [comment]
Excellent, I'll merge this and publish it in the beta soon.

**Comment by tidzo** [comment]
Sorry to ask a a question on a closed issue, but above you said, "Dynamic columns should pretty much work when modifying the columns property with push or pop for example" but I've been unable to get that to work.  My requirement is to imperatively add columns (ideally to an entirely empty grid) and later remove them and refresh the data source.  I've tried doing something like

`newCol=document.createElement('data-table-column');
newCol.name="foo"; //also tried setAttribute;
grid.columns.push(newCol);`

and although my new column shows up alongside the others that are there, I can't get it to show up in the grid.  Is this kind of manipulation possible? Thanks!

**Comment by Saulis** [comment]
Hi @tidzo !

I've tested the dynamic columns myself only inside a `dom-repeat` template, but theoretically imperative approach should work also. 

One piece of advice I can give you at least is that you should call the Polymer API `grid.push('columns', newCol);` for the element to be notified of changes correctly.

Secondly, you need to have a `<template>` element for the column at creation time – `<data-table-column>` doesn't support applying templates afterwards at this point.

I'd suggest trying something like this:

``` js
var temp = document.createElement('div');
temp.innerHTML = '<data-table-column name="First Name"><template>[[item.user.name.first]]</template></data-table-column>';

var newCol = temp.querySelector('data-table-column');
grid.push('columns', newCol);
```

If you need more assistance, I'd be happy to have a chat in the [Gitter chat](https://gitter.im/Saulis/iron-data-table?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).

**Comment by Saulis** [comment]
@tidzo did you get it working?

**Comment by depeele** [comment]
Just getting back to using iron-data-table after a sabbatical and it appears that this issue is no longer fixed.

The following, which worked properly with the `feature/dynamic-columns` branch  no longer works properly. The header and first column render as expected, but the dynamic content of the columns is no longer rendered at all:

```
<html>
 <head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="chrome=1" />
  <title>`iron-data-table` test</title>

  <script src="lib/webcomponentsjs/webcomponents-lite.js"></script>

  <link href="lib/polymer/polymer.html" rel="import" />
  <link href="lib/iron-data-table/iron-data-table.html" rel="import" />
 </head>
 <body>
  <section class='main-content'>
   <template id="scope" is="dom-bind">
    <iron-data-table items="{{Aitems}}">
      <!-- column 1 { -->
      <data-table-column>
        <template is="header">th</template>
        <template><div class='A-card'>{{ item.name }}</div></template>
      </data-table-column>
      <!-- column 1 } -->
      <!-- column 2..n { -->
      <template is="dom-repeat" items="{{Bitems}}" as="bItem" index-as="bdex">
        <data-table-column>
          <template is="header">{{bItem.name}}</template>
          <template>
            <div class='A-card'>{{getItem(bdex, index)}}</div>
          </template>
        </data-table-column>
      </template>
      <!-- column 2..n } -->
    </iron-data-table>
   </template>
  </section>

  <script>
  (function() {
    var A = [
        {name:'A1'},
        {name:'A2'},
        {name:'A3'},
        {name:'A4'},
    ];
    var B = [
        {name:'B1', data:['AB1,1','AB1,2','AB1,3','AB1,4']},
        {name:'B2', data:['AB2,1','AB2,2','AB2,3','AB2,4']},
        {name:'B3', data:['AB3,1','AB3,2','AB3,3','AB3,4']},
        {name:'B4', data:['AB4,1','AB4,2','AB4,3','AB4,4']},
    ];
    var $scope  = document.querySelector('#scope');

    $scope.getItem = function(bdex, adex) {
        var b   = Bitems[bdex];
        return b.data[adex];
    };
    $scope.Aitems = A;
    $scope.Bitems = B;
  }());
  </script>
 </body>
</html>
```
