### ISSUE TITLE
Define rootDataHost for event listeners

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#100]
I have a custom element inside of `data-table-column`, which fires an event.
This event should be propagated to the element which contains `iron-data-table` and has a corresponding event handler.
However, when trying to assign listener (via attribute), I see the following warning:

```
[iron-data-table::_createEventHandler]: listener method `_notifyManagerRole` not defined
```

So, `iron-data-table` itself tries to handle an event instead of propagating it correctly.
It seems that there are still some issues with `rootDataHost`.

**Comment by m-nel** [comment]
Having the same problem.

It seems to have been introduced in v1.0.0-beta4. Works correctly with v1.0.0-beta3

**Comment by Saulis** [comment]
Thanks for the report, I'll look into it asap.

Update: Please try the PR #102, should fix the issue.

**Comment by web-padawan** [comment]
@Saulis I tried it out, now works fine. An example is [here](https://sandbox-e0d4b.firebaseapp.com/demo/table/) - click "Action" button.
Thanks!
