### ISSUE TITLE
Shady DOM classes are not applied to data-table-row-detail

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#106]
When not using native shadow DOM, `data-table-row-detail` elements are supposed to be placed outside the local dom of iron-data-table.

But shady DOM classes are not applied at all, which breaks styling (take a look at empty `class`):

![detail](https://cloud.githubusercontent.com/assets/10589913/16478551/109a2228-3ea3-11e6-86ed-001982acba79.png)

It seems that adding following strings (copied from `data-table-cell`) fixes that: 

``` js
          if (this.domHost) {
            Polymer.StyleTransformer.dom(this, this.domHost.tagName.toLowerCase(), this._scopeCssViaAttr, false);
          }
```

**Comment by Saulis** [comment]
Thanks!
