### ISSUE TITLE
Feature request: Allow single selection when click on the list item when multi-selection is enabled

### ISSUE THREAD

**Issue by ashi009** [Saulis/iron-data-table#108]
Multi-selection works great, but it also make sense to allow one quickly selects a single item instead of adding it to the selection.

As we have checkboxes on the left when multiple selection is enabled, it's some kind of convention that one uses a checkbox to select multiple item and revert to single selection when click on the item itself.

I think there could be a attribute for changing the default behavior.

**Comment by Saulis** [comment]
Hi! 

Interesting proposal, are there some popular live apps that demonstrate this convention? Is it usable with small touch devices — is there a possibility that accidental taps on an item will clear the multi-selected values?

**Comment by ashi009** [comment]
One example I can think of is outlook.com.  Which allows you select multiple mails through checkboxes, and revert to view mode by click on a single item.

I think there are other workarounds for small touch device, as long as there are more events could be listen on.  For instance inbox.google.com uses a similar design, but it enters select mode once a single checkbox is selected, and one must quit that mode through app bar, which eliminates the possibility of accidental revert selection.

**Comment by Saulis** [comment]
Right, I see  – I put something together: http://jsbin.com/zitetu/1/edit?html,output , uses branch `item-single-selection` 

Does it behave like you meant?

**Comment by ashi009** [comment]
Thanks for working on this.  It looks fantastic! This is exactly what I want.

**Comment by Saulis** [comment]
OK great, I'll see what I can. I'd like to keep the API as simple as possible so at this point I'm not sure if I'd want to add another parameter (not sure what I would call it).

How would you feel if this behaviour would be included in a "addon" element and usage would be something like:

``` html
<iron-data-table-selection-addon>
  <iron-data-table>
    <data-table-column>
   ...
   </data-table-column>
  </iron-data-table>
</iron-data-table-selection-addon>
```

**Comment by ashi009** [comment]
It looks good to me.

I think another approach is to add a few more events for iron-data-table, say on-select event with distinguishable event targets, and I could implement this feature by myself without introducing any new component.

**Comment by Saulis** [comment]
@ashi009 that's a great idea!

I added a branch `item-selecting-events` for you to try out.

You can then add these listeners:

``` js
table.addEventListener('selecting-item', function(e) {
  e.preventDefault(); // this will cancel the default selection behavior
  table.clearSelection();
  table.selectItem(e.detail.item);
});
```

``` js
table.addEventListener('deselecting-item', function(e) {
  if (table.selectedItems.length > 1 || table.selectedItems[0] !== e.detail.item) {
    e.preventDefault(); // this will cancel the default selection behavior
    table.clearSelection();
    table.selectItem(e.detail.item);
  }
});
```

and that should add the behaviour you're looking for.

**Comment by ashi009** [comment]
Thanks for the fantastic work!
