### ISSUE TITLE
Sorting seems not to work with dataSource

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#113]
When I use `dataSoure` instead of `items`, sorting is not performed.
Don't have enough time to investigate right now, but `sort-direction-changed` event is fired and `sortOrder` property is updated.
I will try to provide a demo later, maybe just using existing `dataSource` demo.

**Comment by Saulis** [comment]
Just making sure we're on the same page here: when using `dataSource`, sorting and filtering is meant to be done inside that function. When setting an array to `items`, actually a function is set as `dataSource` which implements sorting and filtering in-memory.

**Comment by web-padawan** [comment]
I see. Would it be enough just to grab some corresponding code from `arraydatasource.js` and modify that function?

**Comment by Saulis** [comment]
Sure if you want to do the sorting client side.
