### ISSUE TITLE
Selection and detail not working on first item

### ISSUE THREAD

**Issue by gdavalos** [Saulis/iron-data-table#116]
Might be related to #88 

When using the table with either selection or details enabled inside another custom element, clicking on the first row doesn't expand the detail or select the item but every other item works just fine. (I haven't tested if it happens outside too)

Selecting the first item using the checkbox provided by `multiSelection` works just fine though.

Here's a [jsfiddle](https://jsfiddle.net/1hwuwbno/2/) in which you can see what's happening

**Comment by Saulis** [comment]
Thanks for the fiddle, I'll have a closer look asap!

**Comment by Saulis** [comment]
Try this updated fiddle, https://jsfiddle.net/thb5srnx/ or branch `fix-row-click`

**Comment by gdavalos** [comment]
It looks like it works just fine, thanks

**Comment by Saulis** [comment]
Found a regression.
