### ISSUE TITLE
Two way data binding is broken in IE

### ISSUE THREAD

**Issue by Kilometers42** [Saulis/iron-data-table#12]
The two-way binding on the demo page in Internet Explorer 11 doesn't seem to be working. When I update a cell in the "first name" column and then push enter I am getting a console error: Object doesn't support property or method 'startsWith' and the  "first name also" column doesn't update. I tried with both the lite version and the full version of webcomponents.

**Comment by Saulis** [comment]
Hi!

Thanks for the report, looks like IE doesn't support String.startsWith(), I need to change that to indexOf() instead ASAP.

**Comment by Saulis** [comment]
Please let me know if you encounter any other issues with IE11.

**Comment by Kilometers42** [comment]
Will do and thanks!
