### ISSUE TITLE
Feature Request: Auto-refresh for the data-table

### ISSUE THREAD

**Issue by rosepriya-jk** [Saulis/iron-data-table#127]
It would be good if there is an auto-refresh property for the iron-data-table which can be enabled to refresh the data in grid automatically. If you think this is a valid request, then I shall raise a PR for the same.

**Comment by Saulis** [comment]
Hi!

What do you mean by auto-refresh? An interval which calls `refreshItem()` or something that acts when an item is changed through two-way binding?

**Comment by rosepriya-jk** [comment]
yes, the `autoRefresh` property when enabled, would refresh the list by triggering the `dataSource`

**Comment by wilyrus** [comment]
Yes, it would be great to to have prop to change table automatically on

>  item is changed through two-way binding

**Comment by Saulis** [comment]
@rosepriya-jk @wilerus what do you guys think about: https://github.com/Saulis/iron-data-table/pull/141 ?

**Comment by dannick-montanede** [comment]
hi, I don't understand how and where to use auto-refresh ? 

I tried : <iron-data-table items="[[dataSourceTab1.items]]" auto-refresh> but it doesn't working 
` <iron-data-table items="[[dataSourceTab1.items]]" auto-refresh>`
