### ISSUE TITLE
provide an event on row click with enough details

### ISSUE THREAD

**Issue by dam0vm3nt** [Saulis/iron-data-table#129]
Is it possibile to let `iron-data-table` fire an event when an user clicks on a row with enough `details` to know which row / item has been clicked (something like `iron-activate`) ?

This is usefull when using a table  and a click on a row will do something with that row. 

Note that observing `selectedItem' is not enough because if the user clicks again on a selected row the event would not be fired (the selection will not change).

**Comment by Saulis** [comment]
Hi!

In `v1.0.1` (released this morning) there is events like `selecting-item` and `deselecting-item` fired. They contain the `item` which has been clicked. Are these events suitable for you? (Keeping in mind `selectionEnabled` must be set.

**Comment by dam0vm3nt** [comment]
hi, will `selecting-item` or `deselecting-item` be fired even if the item is already selected (in single selection mode) ? In that case it will be ok.

**Comment by Saulis** [comment]
Yes, `deselecting-item` will fire when user clicks on a selected row.

**Comment by dam0vm3nt** [comment]
ok, it is closed for me then
