### ISSUE TITLE
Consistency "PolymerElements" vs "polymerelements" in bower.json for webjars usage

### ISSUE THREAD

**Issue by bartolom** [Saulis/iron-data-table#130]
This is a similar issue to the one that I submitted to the Polymer project https://github.com/PolymerLabs/tedium/issues/47 and it would be nice if the iron-data-table would also use the consistent "PolymerElements" version. 

This would make it easier to use iron-data-table with webjars.org

I'll submit a pull request

**Comment by Saulis** [comment]
Closed by #131
