### ISSUE TITLE
Feature Request: Typescript definition file for better Angular2 integration

### ISSUE THREAD

**Issue by DzmitryShylovich** [Saulis/iron-data-table#134]
I am, as a lot of Angular 2 developers, working more and more with Typescript. And, as you may know, Typescript needs typings for external libraries. So it would be great if you could add the typings within the npm module.

Should I move this to https://github.com/Saulis/angular2-iron-data-table ?

**Comment by Saulis** [comment]
This issue was moved to Saulis/angular2-iron-data-table#4
