### ISSUE TITLE
Bug: Load spinner hangs on remote data source

### ISSUE THREAD

**Issue by itsjustbrian** [Saulis/iron-data-table#135]
Happens pretty much exclusively when moving down with the scrollbar far enough to cause loading, waiting till that loading is complete, and then moving back up to the top with the scrollbar. Loading then hangs here.

First noticed it in my own project but found it's actually reproducible on the provided remote data demo https://saulis.github.io/iron-data-table/demo/index.html

Tested in firefox, chrome.

**Comment by gildean** [comment]
I can also see this when using plain `items="{{items}}"`.
The bigger the list, the easier the bug is to trigger (as more loading from cache happens and there's probably some race-condition between the spinner showing up with an animation and the cache being already populated...or something)
