### ISSUE TITLE
selection behavior when" multi-selection" and no "selection-enabled" 

### ISSUE THREAD

**Issue by s-trooper** [Saulis/iron-data-table#138]
it would be consistent with current "multi-selection" behavior if no "selection-enabled" that click on checkbox select the row like click on top/column checkbox select all/none rows. as side effect, this way one can focus rows without select them without "selecting-item" workaround.

IMHO normal, in all other grids i know, focus row/cell does not select row. the selection should be distinct act like clicking on checkbox or press key and such things. but practically when above would be implemented one would have the this behavior.

**Comment by Saulis** [comment]
Hi!

Good point, haven't actually noticed before this inconsistent behaviour. Thanks!
