### ISSUE TITLE
Cannot use more than one table per page

### ISSUE THREAD

**Issue by brysonthor** [Saulis/iron-data-table#144]
When i use two of these on one page the second doesn't render properly.

**Comment by Saulis** [comment]
Hmm, seems to be working for me in the demos and in here: http://jsbin.com/yekaru/edit?html,output

Can you modify the jsbin so that the issue reproduces?

**Comment by brysonthor** [comment]
true, I wasn't able to get the jsbin to do it, it must be something else that is causing the second table to appear when i remove the first. I'll re-report if I can get some more specifics
