### ISSUE TITLE
Item expanding event is not fired when using custom expand toggle

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#145]
I use a custom expand toggle element bound to `{{expanded}}` property, without `details-expanded` attribute (because I only need to show details when clicking on element, not the whole row).
But `expanding-item` event is not fired  due to this row: 

```
if (this.rowDetail && this.detailsEnabled) {
```

Maybe instead of firing this event inside of click handler we should observe `expanded`?

```
      _expandedChanged: function (expanded, oldExpanded) {
        if (expanded === true && oldExpanded === false) {
          console.log('expanded');
        } else if (expanded === false && oldExpanded === true) {
          console.log('collapsed');
        }
      }
```

**Comment by Saulis** [comment]
Hi!

Yeah, the `expanding-item` is supposed to be fired only when user has clicked on a row to expand it. I guess we should make `_expandedItems` public and put `notify: true` on it.

**Comment by Saulis** [comment]
@web-padawan could you try out how `expose-expanded-items` branch work for you? `expandedItems` is now public and you should be able to observe that for changes.

**Comment by web-padawan** [comment]
Thanks, I'll take a look.

**Comment by Saulis** [comment]
@web-padawan any luck?

**Comment by web-padawan** [comment]
Looks good, but what if someone changes `expanedItems` from outside?
I already implemented this in `brainy-table`, however. Will debug there.
Will close the issue now, it's up to you to make a decision.
