### ISSUE TITLE
Grid content not showing in Firefox

### ISSUE THREAD

**Issue by miguelamello** [Saulis/iron-data-table#149]
Hi Saulis,

First of all. Congratulations for the great web component. Well, do you have any clue why data-table-cell do not show its content? Actually, the rows are placed, but in blank.

Best regards,

**Comment by miguelamello** [comment]
This examples works perfectly...

http://jsbin.com/hekuwe/edit?html,console,output

**Comment by miguelamello** [comment]
I see no console errors at all.

**Comment by Saulis** [comment]
Hi!

Can you share an example app where you have the problems?

**Comment by miguelamello** [comment]
Sure... take a look at http://diretonamao.com

**Comment by miguelamello** [comment]
I've checked it out and cell content is there, but does not is visible in the following browsers: Firefox (Linux and Windows versions) and MS Edge (I guess IE also). On Opera and Chrome shows properly. Weird. :-)

**Comment by miguelamello** [comment]
Hi Saulis,

I really cant figure out why the iron-data-table content does not show in Firefox. 

http://diretonamao/

The remote datasource is loaded into the table, but the content does not show. If you click in the checkboxes, the "subtotal" sums up, showing the date is holding the data. 

Any tip?

Than you man...

**Comment by miguelamello** [comment]
`
<dom-module id="app-home">

  <template>

    <style include="iron-flex iron-flex-reverse iron-flex-alignment"></style>
    <style include="iron-flex-factors iron-positioning"></style>
    <style include="shared-styles"></style>

    <style>

      :host {
        height: 100%;
      }

      #app_pane {
        height: 100%;
      }

      .actions {
        text-decoration: none;
        color: inherit;
      }

      #login_submit_button {
        margin-top: 20px;
        margin-bottom: 20px;
        float: right;
      }

      .alert_box {
        margin: 10px;
        padding: 10px;
        background-color: #F44336;
        color: #FFFFFF;
      }

      .message_box {
        margin: 10px;
        padding: 10px;
        background-color: #EEEEEE;
      }

      .form_box {
        margin: 10px;
      }

      paper-item {
        font-size: 12px;
        white-space: nowrap;
        margin-right: 10px;
      }

      paper-input-container {
        min-width: 300px;
      }

      #products_table data-table-row:not([header]):hover {
        background-color: #EEEEEE;
      }

      #products_table .product-column {
        text-align: left;
      }

      .order_subtotal {
        font-weight: bold;
        font-size: 1.8em;
        margin-right: 15px;
      }

      .align_center {
        text-align: center;
      }

      .send_button_padding {
        padding: 25px;
      }

      .qtd_input {
        width: 20px;
      }

      #delivery {
        width: 50%;
        border: 1px solid #616161;
      }

      #delivery tr:first-child {
        background-color: #616161;
        color: #FFFFFF;
      }

      .product_image {
        margin-left: 5px;
      }

      iron-data-table data-table-row-detail {
        height: 200px;
      }

      iron-data-table data-table-row-detail .detail {
        width: 100%;
        padding-bottom: 15px;
        display: flex;
        justify-content: space-around;
        align-items: center;
      }

      @media (min-width: 1000px) {
      	.page {
          margin: 30px;
        }

        #delivery {
          width: 70%;
        }
      }

      @media (max-width: 400px) {

        .alert_box {
          margin: 0px;
          padding: 10px;
          background-color: #F44336;
          color: #FFFFFF;
        }

        .message_box {
          margin: 0px;
          padding: 10px;
          background-color: #EEEEEE;
        }

        .form_box {
          margin: 5px;
        }

        #delivery {
          width: 90%;
        }
      }

    </style>

    <paper-toast id="toast" duration="3000"></paper-toast>

    <div id="app_pane" class="layout vertical">
      <div class="page">
        <form is="iron-form" id="pedido_form">

          <div class="alert_box">
            Prezado, nossa ferramenta ainda está em fase de
            implementação e testes, mas nos próximos dias já
            estará permitindo a encomenda do material escolar.
            Obrigado.
          </div>

          <div class="message_box">
            Olá, obrigado por prestigiar o DIRETONAMAO como uma opção de compra
            do material escolar do seu filho. A ferramenta é bem simples. Siga o
            passo-a-passo de como usar. Qualquer duvida entre em contato pelos
            canais abaixo.
            <br>
            <br>
            WhatsApp: 22 99998-3366<br>
            Email: contato@diretonamao.com<br>
            Fixo: 22 3053-5723<br>
            Facebook: facebook.com/diretonamao<br>
            <br>
            ATENÇÃO:<br>
            <br>
            * Caso você não encontre a lista específica da escola/série do seu filho(a),
            você poderá utilizar a LISTA GERAL. Você também pode nos enviar por email
            a lista do seu filho, para que possamos disponibilizar no sistema.<br>
            <br>
            * Utilize o navegador Google Chrome, caso encontre alguma dificuldade
            em outros navegadores.<br>
            <br>
            <b>Passo 1)</b> Selecione a lista de material escolar da escola/série do seu
            filho(a), ou utilize a LISTA GERAL.
          </div>

          <div class="form_box align_center">
            <paper-dropdown-menu
              id="series_select"
              name="familia"
              label="Escolha uma serie..."
              noink
              no-animations
              no-label-float
              on-iron-select="get_products"
              auto-validate
              error-message="Por favor escolha uma serie"
              required>
              <paper-listbox class="dropdown-content" attr-for-selected="value" selected="18">
                <template is="dom-repeat" items='[[series]]' as="serie">
                  <paper-item value="[[serie.id_familias]]">[[serie.nome_familias]]</paper-item>
                </template>
              </paper-listbox>
            </paper-dropdown-menu>
          </div>

          <div class="message_box">
            <b>Passo 2)</b> Na planilha abaixo, identifique os produtos desejados, e marque-os
            para encomenda-los. Você poderá também modificar a quantidade desejada.
            Perceba que alguns produtos são em forma de kit, atendendo a quantidade
            solicitada pela escola. Alguns produtos aparecem repetidos porque são de fabricantes
            diferentes, e possuem preços diferentes.
          </div>

          <div class="form_box">
            <iron-data-table
              id="products_table"
              size="100000"
              items="[[products]]"
              on-selected-items-changed="selectedItems"
              multi-selection
              selection-enabled>
              <template is="row-detail">
                <div class="detail">
                  <img
                    id="img[[item.image_id]]"
                    src="{{imageUrl(item.image_id)}}"
                    height="200px"
                  />
                </div>
              </template>
              <data-table-column name="QTD">
                <template>
                  <paper-input
                    type="string"
                    id="[[item.index]]"
                    class="qtd_input"
                    value="1"
                    maxlength="2"
                    allowed-pattern="[0-9]"
                    on-change="check"
                    on-tap="prevent_default"
                    no-label-float>
                  </paper-input>
                </template>
              </data-table-column>
              <data-table-column name="PRODUTO" flex="50">
                <template>
                  <div class="product-column">
                    [[item.nome_produtos]]
                    <iron-icon
                      id="[[item.image_id]]"
                      class="product_image"
                      icon="image:camera-alt"
                      title="ver imagem"
                      hidden$="{{check_state(item.image_hidden)}}"
                      on-click="show_image">
                    </iron-icon>
                  </div>
                </template>
              </data-table-column>
              <data-table-column name="VALOR">
                <template>[[item.valor_venda_produtos]]</template>
              </data-table-column>
            </iron-data-table>
          </div>

          <div class="form_box">
            <table border="0" width="100%">
              <tr>
                <td align="right">
                  <b>Subtotal:</b>
                </td>
                <td align="right" width="1px">
                  <span class="order_subtotal">[[order_subtotal]]</span>
                </td>
              <tr>
            </table>
          </div>

          <div class="message_box">
            <b>Passo 3)</b> Ótimo, você já definiu a série e os produtos que deseja.
            Agora você precisa preencher mais algumas informações. Vamos
            começar pelo tipo de delivery que você deseja.
            <br><br>
            GRATUITO: Entregamos, apenas em CABO FRIO, na porta da escola do seu filho(a),
            em horario à combinar. Caso você seja de outra cidade, podemos combinar um local
            e hora, em CABO FRIO, para a entrega dos produtos.
            <br><br>
            PAGO: Entregamos no endereço que você desejar. O valor do delivery dependerá
            da cidade de destino, que será fornecida por você mais adiante. O valor referente
            a cidade será adicionado ao valor do pedido.
            <br><br>
            <table id="delivery" border="0" cellpadding="5" align="center">
              <tr><td>CIDADE</td><td>VALOR</td></tr>
              <tr><td>CABO FRIO</td><td>10,00</td></tr>
              <tr><td>SÃO PEDRO DA ALDEIA</td><td>15,00</td></tr>
              <tr><td>ARRAIAL DO CABO</td><td>15,00</td></tr>
              <tr><td>ARMAÇÃO DOS BUZIOS</td><td>20,00</td></tr>
            </table>
            <br>
          </div>

          <div class="form_box align_center">
            <paper-radio-group id="delivery_radio" selected="gratuito">
              <paper-radio-button name="gratuito">GRATUITO</paper-radio-button>
              <paper-radio-button name="pago">PAGO</paper-radio-button>
            </paper-radio-group>
          </div>

          <div class="message_box">
            <b>Passo 4)</b> Agora você precisa preencher mais algumas informações
            para que possamos gerar seu pedido. Caso você tenha optado pelo Delivery
            GRATUITO, preencha o endereço de sua residência, que será utilizado
            para gerar o pedido. Caso você tenha optado pelo Delivery PAGO, preencha
            o endereço aonde os produtos deverão ser entregues.
          </div>

          <div class="form_box">
            <paper-input
              name="nome"
              label="Nome Completo"
              maxlength="100"
              auto-validate
              error-message="Por favor digite seu nome"
              required>
            </paper-input>
            <paper-input
              name="cpf"
              label="CPF"
              maxlength="11"
              minlength="11"
              allowed-pattern="[0-9]"
              auto-validate
              error-message="Por favor digite seu CPF"
              required>
            </paper-input>
            <paper-input
              name="celular"
              label="Celular/Fixo (DDD + Numero)"
              maxlength="11"
              minlength="11"
              allowed-pattern="[0-9]"
              auto-validate
              error-message="Por favor digite seu celular/fixo"
              required>
            </paper-input>
            <paper-input
              type="email"
              name="email"
              label="Email"
              maxlength="50"
              auto-validate
              error-message="Por favor digite seu email"
              required>
            </paper-input>
            <paper-input
              name="logradouro"
              label="Logradouro"
              maxlength="250"
              auto-validate
              error-message="Por favor digite seu logradouro"
              required>
            </paper-input>
            <paper-input
              name="numero"
              label="Numero"
              maxlength="5"
              minlength="1"
              allowed-pattern="[0-9]"
              auto-validate
              error-message="Por favor digite o numero"
              required>
            </paper-input>
            <paper-input
              name="complemento"
              label="Complemento"
              maxlength="100">
            </paper-input>
            <paper-input
              name="bairro"
              label="Bairro"
              maxlength="100"
              auto-validate
              error-message="Por favor digite seu bairro"
              required>
            </paper-input>
            <paper-dropdown-menu
              name="municipio"
              label="Municipio"
              noink
              no-animations
              auto-validate
              error-message="Por favor escolha um municipio"
              required>
              <paper-listbox
                id="municipio_select"
                class="dropdown-content"
                attr-for-selected="value">
                <paper-item value="382">ARMAÇÃO DOS BUZIOS</paper-item>
                <paper-item value="389">ARRAIAL DO CABO</paper-item>
                <paper-item value="824">CABO FRIO</paper-item>
                <paper-item value="4809">SÃO PEDRO DA ALDEIA</paper-item>
              </paper-listbox>
            </paper-dropdown-menu>
            <paper-input
              name="cep"
              label="CEP"
              maxlength="8"
              minlength="8"
              allowed-pattern="[0-9]"
              auto-validate
              error-message="Por favor digite seu CEP"
              required>
            </paper-input>
            <paper-input
              name="uf"
              label="UF"
              maxlength="2"
              value="RJ"
              readonly
              auto-validate
              error-message="Por favor digite a UF"
              required>
            </paper-input>
          </div>

          <div class="message_box">
            <b>Passo 5)</b> Agora que vocé já preencheu todas as informações para gerar
            seu pedido, é necessario que você leia com atenção o texto a seguir,
            marcando que concorda e aceita os termos mencionados.
            <br>
            <br>
            1) Informamos que alguns itens, como os especificados abaixo, podem
            compor a lista escolar do seu filho(a), e você deverá providenciar
            por conta própria. Os itens são: Fantasia infantil; Foto
            do aluno; Jaleco branco; Escovas de dentes; Creme
            dental; Capa de chuva; Toalha de banho; Chinelo de borracha; Copo
            plástico com alça e bico; Lençol; Fronha; Travesseiro; Tapete emborrachado;
            Fralda descartável; Lenço umedecido; Pomada para assaduras e Lenço de papel.
            Verifique a lista do seu filho(a) junto à escola.
            <br>
            <br>
            2) O pedido realizado nesta ferramenta, se refere a uma encomenda e
            será confirmada pela empresa,
            <br>
            <br>
            3) O prazo de entrega dos produtos será combinado diretamente
            <br>
            <br>
            4) Caso você esteja encomendando o "avental", iremos solicitar
            informação sobre o tamanho desejado.
            <br>
            <br>
            5) Caso você esteja encomendando o "Kit de Etiquetas", iremos
            solicitar informação adicional sobre os dados da criança, que devem constar
            na mesma.
            <br>
            <br>
            <paper-checkbox
              name="aceito"
              auto-validate
              error-message="Por favor marque como lido"
              required>
              Concordo e aceito os termos acima.
            </paper-checkbox>
            <br>
            <br>
            <b>Passo 6)</b> Agora, basta enviar seu pedido, e aguardar nosso contato para
            acertar-mos as condições de pagamento e entrega dos produtos. Obrigado.
          </div>

          <div class="form_box align_center">
            <div class="send_button_padding">
              <paper-button class="send_button" on-tap="submit">ENVIAR</paper-button>
            </div>
          </div>
        </form>
      </div>
      <app-rodape></app-rodape>
    </div>
  </template>

  <script>

    (function (root) {

      Polymer({

        is: 'app-home',

        properties: {

          series: {
            type: Array,
            value: function() { return [] },
            notify: true
          },

          products: {
            type: Array,
            value: function() { return [] },
            notify: true
          },

          order_subtotal: {
            type: String,
            value: function() { return '$ 0,00' },
            notify: true
          },

          expanded_item: {
            type: Number,
            value: function() { return 0 }
          }

        },

        attached: function() {
          this.domHost.current_obj = this;
          root.Cookies.remove('accessToken');
          this.get_series();
        },

        behaviors: [ app_behaviors.common_behavior ],

        check_state: function(state) {
          return state;
        },

        get_series: function() {
          var self = this;
          this.domHost.$.app_proxy.call_server(
            'getFamilies.php',
            'POST'
          ).then(function(xhr) {
            var nodes = [];
            if (xhr.response.length) {
              for (var i in xhr.response) {
                nodes[i] = [];
                nodes[i]['id_familias'] = xhr.response[i]['id_familias'];
                nodes[i]['nome_familias'] = xhr.response[i]['nome_familias'];
              }
            }
            self.series = nodes;
            return xhr;
          });
        },

        get_products: function(e, detail) {
          var self = this;
          this.set_order_subtotal(0);
          this.domHost.$.app_proxy.call_server(
            'getFamilyProducts.php',
            'POST',
            'familyID=' + detail.item.value,
            true
          ).then(function (xhr) {
            self.products = xhr.response;
            self.domHost.set('isLoading', false);
            return xhr;
          });
        },

        check: function(e) {

          if (!parseInt(e.detail.sourceEvent.path[0].value)) {
            e.detail.sourceEvent.path[0].value = 1;
          }

          this.products[e.path[0].id]['qtd'] = e.detail.sourceEvent.path[0].value;

          if (this.$.products_table.selectedItems.inverted) {
            this.get_raw_order_subtotal();
          } else {
            if (this.$.products_table.selectedItems.length > 0) {
              this.get_order_subtotal(this.$.products_table.selectedItems);
            }
          }

        },

        selectedItems: function(e) {

          if (e.detail.value !== null) {
            if (typeof e.detail.value.inverted == 'boolean') {
              if (e.detail.value.inverted) {
                this.get_raw_order_subtotal();
              } else {
                this.set_order_subtotal(0);
              }
            } else {
              if (typeof e.detail.value == 'object') {
                if (e.detail.value) {
                  if ('indexSplices' in e.detail.value) {
                    e.detail.value['indexSplices'][0]['object'].inverted = false;
                    this.get_order_subtotal(e.detail.value['indexSplices'][0]['object']);
                  }
                }
              }
            }
          }

        },

        get_raw_order_subtotal: function() {

          var sum = 0;
          for (var i in this.products) {
            sum += parseFloat(this.products[i]['valor_produtos'] * this.products[i]['qtd']);
          }
          this.set_order_subtotal(sum);

        },

        get_order_subtotal: function(items) {
          if ('length' in items) {
            if (items.length) {
              var sum = 0;
              for (var i in items) {
                if (typeof items[i] == 'object') {
                  if (items[i].constructor === Object) {
                    sum += parseFloat(items[i]['valor_produtos'] * items[i]['qtd']);
                  }
                }
              }
              this.set_order_subtotal(sum);
            } else {
              this.set_order_subtotal(0);
            }
          }
        },

        set_order_subtotal: function(val) {
          this.order_subtotal = '$' + val.toFixed(2).toString();
        },

        prevent_default: function(e) {
          e.preventDefault();
          e.stopPropagation();
        },

        show_image: function(e) {
          e.preventDefault();
          e.stopPropagation();
          if (this.expanded_item === e.path[8].item.id_produtos) {
            this.$.products_table.collapseItem(e.path[8].item);
            this.expanded_item = 0;
          } else {
            this.expanded_item = e.path[8].item.id_produtos;
            this.$.products_table.expandItem(e.path[8].item);
          }
        },

        imageUrl: function(id) {
          var url = '';
          url = this.domHost.$.local_config.apiHost;
          url += '/includes/get_product_image.php?id='+id;
          return url;
        },

        submit: function(event) {

          if (/diretonamao\.com/.test(window.location.host)) {
            this.$.toast.show({ text: 'Ainda está em fase de testes. Aguarde mais alguns dias. Obrigado.'});
            return false;
          }

          var self = this;
          this._trim_paper_input(Polymer.dom(this.root).querySelectorAll('paper-input'));

          if (this.$.series_select.selectedItem.value == undefined) {
            this.$.toast.show({ text: 'Selecione uma serie.'});
            return false;
          }

          if (this.$.products_table.selectedItems.inverted === false) {
            if (this.$.products_table.selectedItems.length === 0) {
              this.$.toast.show({ text: 'Selecione algum produto.'});
              return false;
            }
          }

          if (this.$.delivery_radio.selected === undefined) {
            this.$.toast.show({ text: 'Selecione um delivery.'});
            return false;
          }

          if (this.$.pedido_form.validate()) {

            var form_items = this.$.pedido_form.serialize();
            form_items.familia = this.$.series_select.selectedItem.value;
            form_items.municipio = this.$.municipio_select.selected;
            for (var i in this.products) { this.products[i]['required'] = 0; }

            if (!this.validaCPF(form_items.cpf)) {
              this.$.toast.show({ text: 'CPF inválido.'});
              return false;
            }

            if (this.$.products_table.selectedItems.inverted) {
              for (var i in this.products) {
                this.products[i]['required'] = 1;
              }
            } else {
              var items = this.$.products_table.selectedItems;
              for (var i in items) {
                if (typeof items[i] == 'object') {
                  if (items[i].constructor === Object) {
                    for (var j in this.products) {
                      if (this.products[j]['id_produtos'] == items[i]['id_produtos']) {
                        this.products[i]['required'] = 1;
                      }
                    }
                  }
                }
              }
            }

            form_items.products = this.products;
            this.domHost.$.app_proxy.call_server(
              'saveWebOrder.php',
              'POST',
              { data: JSON.stringify(form_items) },
              true
            ).then(function(xhr) {
              self.domHost.set('isLoading', false);
              if (xhr.response.data) {
                self.$.pedido_form.reset();
                self.$.series_select.selectedItem.value = undefined;
                self.$.delivery_radio.selected = undefined;
                self.set('products', []);
                self.$.products_table.clearCache();
                self.$.toast.duration = 5000;
                self.$.toast.show({
                  text: 'Seu pedido foi processado. Aguarde nosso contato. Obrigado.'
                });
                self.$.toast.duration = 3000;
              } else {
                self.$.toast.duration = 5000;
                self.$.toast.show({
                  text: 'Não conseguimos processar seu pedido. Caso o problema persista, ' +
                        'entre em contato conosco. Obrigado.'
                });
                self.$.toast.duration = 3000;
              }
              return xhr;
            });
          } else {
            this.$.toast.show({ text: 'Verifique todos os campos.'});
            return false;
          }
        }

      });

    })(this);


  </script>

</dom-module>
`

**Comment by Saulis** [comment]
Could you send me the whole app including `bower.json` and other files needed to run it locally?

Thanks!

**Comment by miguelamello** [comment]
Sure... great!
[app.zip](https://github.com/Saulis/iron-data-table/files/501407/app.zip)

**Comment by miguelamello** [comment]
Hi Saulis,

Well, this issue is completely fixed. I've fixed it applying two actions:

1) Changing "webcomponents.min.js" for "webcomponents-lite.min.js". Okay, that's my fault indeed. I should have paid attention to Polymer Manual, and have used webcomponents-lite.min.js in my project. 

2) Got the iron-data-table to update faster and securely by using this.set('myArray', someArray). 

Thank you... cheers.

**Comment by Saulis** [comment]
OK great!
