### ISSUE TITLE
Selecting All items in the table

### ISSUE THREAD

**Issue by miguelamello** [Saulis/iron-data-table#150]
Hi. There is some way to fire an event when all items in the table are selected? I'm using "on-selected-items-changed" for each row, but how to activate the colunm iron-data-checkbox for all the itens?

**Comment by Saulis** [comment]
Hi!

You can listen to `selected-items-changed` event on the table element (instead of each row separately). When `selectedItems.inverted` is `true` and `selectedItems.length` is `0`, all the items are selected. Also, when `selectedItems.inverted` is `false` and `selectedItems.length` equals `table.size` all the items are selected.

If you need to programmatically select all the items, call `table.selectAll()`

**Comment by miguelamello** [comment]
Hi Saulis, 

Thank you for replying. Hey, I'm already listening to selected-items-changed event on the table element, as shown below:

```
<iron-data-table
    id="products_table"
    size="100000"
    items="[[products]]"
    on-selected-items-changed="selectedItems"
    multi-selection
    selection-enabled>
... other elements...
</iron-data-table>
```

However, "on-selected-items-changed" does not return all the items when the header checkbox is clicked. It does return the items when the row checkbox is clicked indeed. 

```
selectedItems: function(e) {
          if (typeof e.detail.value == 'object') {
            if (e.detail.value) {
              if ('indexSplices' in e.detail.value) {
                console.log(e.detail.value['indexSplices'][0]['object']);
              }
            }
          }
        }
```

Do you see? I'm able to get all the selected items in the above handler, when the row checkbox is clicked, but when the header checkbox is clicked, no items are returned. I'm missing something? The is a way to reach the column iron-data-checkbox directly, and listen to its checked event? 

Hope all this helps you make the component better yet. :-)

Best regards,

Miguel

**Comment by miguelamello** [comment]
Take a look at http://diretonamao.com

**Comment by miguelamello** [comment]
I guess I have figure out the situation. Thank you man.

**Comment by justinmandac** [comment]
Hi @miguelamello !
How did you fix this issue?

**Comment by therealweezel** [comment]
Hi @Saulis,
I'm having the exact same problem. The selectedItems object is null when you click the column header checkbox to select all. Is there a fix for this or what is the solution to get it working?
