### ISSUE TITLE
Server Send Events and iron-data-table

### ISSUE THREAD

**Issue by lousley** [Saulis/iron-data-table#151]
Hi 

I have a question. In our project we have a server send event mechano to fill a datatable. the result comes every time into an polymer array and on every change of the array we will clean the datatable and shows the new records.
Is it possible to make this with iron-data-table to? 

Thx 4 help.

**Comment by Saulis** [comment]
Hi!

I'm not entirely sure got the question... there is a property `items` which you can set an array to, and when you replace the value, the data gets refreshed, right? Is that what you're trying to do but have some issues?

**Comment by lousley** [comment]
Hi!

Thx 4 answer. I test it with items and thats ok. But can i do this also with datasource? Because i need the infinite scrolling. :)

**Comment by Saulis** [comment]
Sure, you can call `clearCache()` to refresh items when using a `dataSource`. See the API docs here: http://saulis.github.io/iron-data-table/#iron-data-table:method-clearCache

**Comment by lousley** [comment]
OK, i will test it! Thx 4 help!

**Comment by Saulis** [comment]
I'm gonna close the issue for now, feel free to reopen if something pops up.
