### ISSUE TITLE
filter feature broke after hitting no result

### ISSUE THREAD

**Issue by ashi009** [Saulis/iron-data-table#158]
**How to reproduce**
1. Go to https://saulis.github.io/iron-data-table/demo/filtering.html
2. Scroll down the list (optional, but it will break for different reasons.)
3. Input "ttttt"
4. Now the iront-data-table is broken.

I didn't look too deep into this, and here are my findings:
- `_loadPage()` tries to load page `1` from the array datasource.
- array-datasource.js will filter the items, and call the `cb()` (`sucess()` from `_loadPage()`) with an empty array when there is no match.
- `_loadPage()` will iterate through this empty array with out of boundary indices then fill `undefined` to `this.set('_cachedItems.' + index, item)`.
- iron-list will break by these `undefined` items.

**Comment by Saulis** [comment]
Thanks for the report!

There seems to be a check that fails when the returned `size` is falsey, can you try out if the branch `fix/filter-zero-size` fixes all the issues for you?

**Comment by ashi009** [comment]
Thanks for the quick fix!

I've created a demo at  http://jsbin.com/zisojebuge/edit?html,output, and it looks good!

**Comment by ashi009** [comment]
Scratch that.  I might have tested with wrong branch.  Let me apply the patch to my project and see.

**Comment by ashi009** [comment]
Yep, this fixed the issue!
