### ISSUE TITLE
array-datasource: Unable to filter by boolean attribute

### ISSUE THREAD

**Issue by lluisgener** [Saulis/iron-data-table#159]
When you bind a column to a boolean attribute, when the filter-value takes the value **false**, filtering is not working correctly due to null checks with **!** operator.

`array-datasource.js Line 12`

`} else if (!value || value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
          return false;
        }
`

It works applying this fix:

`} else if (value == null || value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
          return false;
        }
`

**Comment by Saulis** [comment]
Thanks! Should be fixed in the next version.
