### ISSUE TITLE
Filtering of null values

### ISSUE THREAD

**Issue by lluisgener** [Saulis/iron-data-table#168]
When a column has a null value, ArrayDataSource filtering raises an exception. I have fixed it faking an empty string value to the value variable when it's null or undefined. 

    return Array.prototype.filter.call(items, function(item, index) {
      for (var i = 0; i < filter.length; i++) {
        var value = Polymer.Base.get(filter[i].path, item);

        /*FIX START*/
        if(value == null || value == undefined)
            value = "";
        /*FIX END*/

        if ([undefined, null].indexOf(filter[i].filter) > -1) {
          continue;
        } else if (value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
          return false;
        }
      }
      return true;
    });

**Comment by hankphung** [comment]
Meet same error here 
+1
I've fallback to v1.0.3 to avoid this bug.

**Comment by Saulis** [comment]
Thanks!

Should be now fixed in the `v1.0.5`

**Comment by lluisgener** [comment]
I think it's not correctly fixed. I still have not found what's wrong, but I see no rows at all with the array-datasource fix. I think it's related to empty strings.
