### ISSUE TITLE
Better support for flexible layout

### ISSUE THREAD

**Issue by dam0vm3nt** [Saulis/iron-data-table#17]
Hi there,
when using `iron-data-table` like this:

```
<dom-module id="sample-comp">
 <template>
  <style>
    .div1 { @apply(--layout-vertical); }
    .tbl { @apply(--layout-flex); }
  </style>
  <div class="div1">
     <div>title</div>
     <iron-data-table class="tbl"> ... </iron-data-table>
     <paper-button>button</paper-button>
   </div>
 </template>
</dom-module>
```

No vertical scroll bar will ever be shown. The intent is to let the table occupy all the available space and leave the button below and the title above. I've tryied wrapping the `iron-data-table` inside a div with an overflow set to auto but then the scroll bar will appear but event the header will scroll away.

The only way I've found to make the scroll bar appear correctly so far is to set a fixed height, but this is not the desired behavior.

**Comment by Saulis** [comment]
I think the problem here might be `iron-list`, because it kinda requires an explicit height to be set on the parent. Need to investigate.

**Comment by dam0vm3nt** [comment]
I've found a work-around, this is working (at least in chrome):

```
<dom-module id="sample-comp">
 <template>
  <style>
    .div1 { @apply(--layout-vertical); }
    .div2 { position:relative; overflow:auto; @apply{--layout-flex);  }
    .div3 { position:absolute;left:0;right:0;top:0;bottom:0;}
    .tbl { height:100%; }
  </style>
  <div class="div1">
     <div>title</div>
      <div class="div2">
       <div class="div3">      
          <iron-data-table class="tbl"> ... </iron-data-table>
       </div>
      </div>
     <paper-button>button</paper-button>
   </div>
 </template>
</dom-module>
```

**Comment by Saulis** [comment]
Could you try branch `feature/flex-height`, it's a bit hacky still, but I don't know if we can make it work without setting an explicit height for a parent. You see, the list  container height should flex-grow when the list contents grow, but it has `overflow: auto` so it kinda prevents the list container from growing. I don't know if there's any way around it.

These are the styles I used: 

``` html
<style is="custom-style">
      .div1 {
        height: 600px; //explicit container height.
        @apply(--layout-vertical);
      }

      .tbl {
        height: 100%;
      }
</style>
```

**Comment by dam0vm3nt** [comment]
could you please also merge the null-item fix in ? 

BTW : would you also mind creating a style module for `iron-data-table` ?

**Comment by dam0vm3nt** [comment]
I realize that my latest comment was misleading. I was asking if you could merge the null-item fix in feature/flex-height branch because otherwise I'm not able to check it.

**Comment by Saulis** [comment]
OK I rebased the branch, also added a new version, so styles:

``` html
<style is="custom-style">
      .div1 {
        height: 600px;
        @apply(--layout-vertical);
      }

      .tbl {
        @apply(--layout-flex);
      }
    </style>
```

seems to work now.

**Comment by dam0vm3nt** [comment]
works like a charm now! TNX!

**Comment by Saulis** [comment]
Great! I'll just keep this issue open until I've merged the changes to master

**Comment by Saulis** [comment]
And, I'll be adding also a style module, as you requested. See #26

**Comment by dam0vm3nt** [comment]
Well, thanks! Will you merge those two into 1.0 ?

**Comment by Saulis** [comment]
Yes, definitely, I'll try to get them in the next (beta) release.

**Comment by userquin** [comment]
To make iron-data-table grows vertically to fill all available space, the user must wrap the table inside a container with this style:

``` css
[iron-data-table-wrapper] {
  height: calc(100vh);
}
```

If the page has h1, paper-header-panel or similar, just substract the height:

``` css
[iron-data-table-wrapper] {
  height: calc(100vh - 96px);
}
```

Then wrap again the wrapper with another wrapper with this css and substract iron-data-table padding:

``` css
[iron-data-table-wrapper-wrapper] {
  height: calc(100% - 10px);
}
```

If you want to include a header and/or a footer, then substract the header size from the first wrapper:

``` css
[iron-data-table-wrapper] {
  height: calc(100% - 65px);
}
```

Finally include a style for iron-data-table with  is height to 100%:

``` css
iron-data-table {
  height: 100%;
}
```

In the last commit in my branch I have included this: 

``` html
<content select="[footer]"></content>
```

and old content now is:

``` html
<content select=":not([footer])"></content>
```

With the last [footer] content I have included, the button can be included inside iron-data-table.

Other trick for buttons will be to use fab-icons with position absolute after iron-data-table markup.

I'm working on 2 examples using paper-header-panel and plain page. Both will be included in demo page.

![fille-vertical-header-2](https://cloud.githubusercontent.com/assets/6311119/14070400/4fc95d70-f4a6-11e5-8f01-c83a6a693367.png)

![fill-vertical-header](https://cloud.githubusercontent.com/assets/6311119/14070383/2330e0e4-f4a6-11e5-8434-d6a5ca860efb.png)

Bye.

**Comment by dam0vm3nt** [comment]
Actually the version I had tested some weeks ago was working perfectly even with a container with "vertical layout" and the table with "flex" and that was all that was needed IMHO.

Is this still happing with your changes ?

**Comment by Saulis** [comment]
What I'm seeing from @userquin are alternative approaches in having a "flexible" height for the table without using CSS flex.

I'm going to go ahead merging the current `flex` solution I've made and releasing it in the next version.

Please feel free to comment or reopen this ticket if issues arise.

**Comment by dam0vm3nt** [comment]
lgtm
