### ISSUE TITLE
data-table-column align center request

### ISSUE THREAD

**Issue by hariprasadiit** [Saulis/iron-data-table#181]
Is there a way to center align column headers?

if not is this possible to have this feature?

**Comment by web-padawan** [comment]
You can use custom header templates like this:
```html
<style>
.th {
  width: 100%;
  text-align: center;
}
</style>

<data-table-column>
  <template is="header">
    <div class="th">Header</div>
  </template>
</data-table-column>
```

However, there is a best practice which you should be aware of:
* Left align text (where appropriate)
* Right align numbers (where appropriate)
* Align titles with data
* Resize columns to data

**Comment by hariprasadiit** [comment]
@web-padawan thanks for the snippet.
