### ISSUE TITLE
No event fired on item selected

### ISSUE THREAD

**Issue by jcrowthe** [Saulis/iron-data-table#19]
It appears like when an item is selected or unselected, the item is properly placed in the selectedItems array, but that no event is fired. The only time an event is fired is when all items are unselected using the checkbox in the header.

Ideas?

**Comment by Saulis** [comment]
Hmm, for me everything seems to fire an event correctly, both `selected-items-changed` and `selected-item-changed` event, in single and multi-selection. What version of `iron-list` are you running?

**Comment by jcrowthe** [comment]
I'm going to guess that this is specific to my code then. I updated to the latest release once I found the error.

Would you confirm that when you assign selected-items="{{selectedItems}}", and you have an observer listening on selectedItems, that the observer is called for each change? I apologize for not specifying that earlier. Specifically, the observer is not fired on anything in my code except for unchecking all boxes using the main checkbox.

**Comment by Saulis** [comment]
Based on your description, I believe you have defined the observer inside the property declaration, and for Array properties, that observer won't detect any mutations. Unchecking the "all" checkbox calls `clear` on `iron-list` and that probably replaces the whole `selectedItems` array, and therefore your observer picks that specific change up.

``` js
properties: {
  selectedItems: {
    type: Array,
    observer: '_selectedItemsChanged'
  }
}
```

instead, you need to have an external observer that observes mutations:

``` js
properties: {
  selectedItems: Array,
},
observers: ['_selectedItemsChanged(selectedItems.*)']
```

If you use single-selection and observe `selectedItem` property, everything works, right?

Another way to hook things up is to listen to the events directly:

``` html
<iron-data-table selection-enabled multi-selection on-selected-items-changed="_selectedItemsChanged">
```

**Comment by jcrowthe** [comment]
You nailed it. Thanks for taking the time to enumerate that!
