### ISSUE TITLE
SortOrder not handled as Array

### ISSUE THREAD

**Issue by userquin** [Saulis/iron-data-table#29]
In iron-data-table sortOrder can be an array to allow multiple sort columns but in data-table-column-sort is handled as plain object. Also sort arrows are not accessible, why just not use paper-icon-button?

Here is a patch allowing configure the sort position in the sortOrder and change div by paper-icon-button to make #sortIcon accessible (only need to configure aria-label, need change iron-data-table also); also allow clear state up-down-newClick sequence -> direction must be reset and propagated to the UI:

``` diff
Index: x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html   (revision )
+++ x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html   (revision )
@@ -10,38 +10,43 @@
         margin: 4px;
       }

-      #sortIcon {
+      paper-icon-button {
-        position: relative;
+          position: relative;
-        width: 24px;
-        height: 24px;
+          opacity: .16;
       }

-      iron-icon {
-        fill: rgba(0, 0, 0, .16);
-        cursor: pointer;
-        padding: 0px;
+      paper-icon-button[active], paper-icon-button:hover, paper-icon-button[focused] {
+          opacity: .84;
+      }
+
+      paper-icon-button ::content iron-icon {
+        padding: 0;
         --iron-icon-width: 24px;
         --iron-icon-height: 24px;
         transition: all .2s;
       }

-      iron-icon[active], iron-icon:hover {
-        fill: rgba(0, 0, 0, .87);
+      paper-icon-button[direction='desc'][active] ::content iron-icon {
+        transform: rotate(-180deg);
       }

-      paper-ripple {
-        color: rgba(0, 0, 0, .54);
+      paper-icon-button[direction]:after {
+        content: attr(sort-order);
+        font-size: 9px;
+        font-weight: bold;
+        position: absolute;
+        right: 4px;
+        bottom: 8px;
       }
-
-      #sortIcon[direction='desc'] iron-icon[active] {
-        transform: rotate(-180deg);
-      }
     </style>

-    <div id="sortIcon" on-tap="_sort" hidden="[[hidden]]" direction$="[[direction]]">
-      <iron-icon active$="[[_isActive(path, sortOrder)]]" icon="arrow-upward"></iron-icon>
-      <paper-ripple class="circle" center></paper-ripple>
-    </div>
+    <paper-icon-button id="sortIcon"
+                       on-tap="_sort"
+                       hidden="[[hidden]]"
+                       icon="arrow-upward"
+                       active="[[_isActive(path, sortOrder)]]"
+                       direction$="[[direction]]"
+                       sort-order$="[[_computeSortOrder(path, sortOrder)]]"></paper-icon-button>

   </template>
   <script>
@@ -49,7 +54,10 @@
       is: 'data-table-column-sort',

       properties: {
-        direction: String,
+        direction: {
+            type: String,
+            notify: true
+        },
         hidden: Boolean,
         path: String,
         sortOrder: {
@@ -59,13 +67,45 @@
       },

       _isActive: function(path, sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          return sortOrder.find(function(item) {
+            return item.path == path;
+          }) !== undefined;
+        }
         return path === sortOrder.path;
       },

       _sortOrderChanged: function(sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          var path = this.path;
+          var sort = sortOrder.find(function(item) {
+            return item.path == path;
+          });
+          if(sort) {
+            this.direction = sort.direction;
+          } else {
+            this.direction = null;
+          }
+        } else {
-        if (sortOrder.path === this.path) {
-          this.direction = sortOrder.direction;
+          if (sortOrder.path === this.path) {
+            this.direction = sortOrder.direction;
+          } else {
+            this.direction = null;
-        }
+          }
+        }
+      },
+
+      _computeSortOrder: function(path, sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          var sort = sortOrder.find(function(item) {
+            return item.path == path;
+          });
+          return sort && sort.order ? sort.order: null;
+        }
+        if (path === sortOrder.path) {
+          return sortOrder.order ? sortOrder.order : null;
+        }
+        return null;
       },

       _sort: function() {
```

**Comment by Saulis** [comment]
Hi! Could you send this patch as a pull request? Thanks!

**Comment by userquin** [comment]
Multi-sort has been included on iron-data-table: see filtering.html in demo directory:

![sort-1](https://cloud.githubusercontent.com/assets/6311119/14066510/94bf19f2-f44b-11e5-9646-5970e9ccabe4.png)

![sort-2](https://cloud.githubusercontent.com/assets/6311119/14066511/9877272e-f44b-11e5-9b93-fb0cee9d57d9.png)

**Comment by userquin** [comment]
Using shadow dom instead shady dom, the icon must be changed/rotated manually, I haven't found a way to access iron-icon inside paper-icon-button and rotate image via CSS.

**Comment by Saulis** [comment]
Thanks for looking into this!

I did intentionally add the `sortOrder` property as an array to provide API for multi-column sorting in the future, but decided to post-pone the actual implementation because I wasn't sure how it should work from the users perspective.

I won't be unfortunately to look into your patch deeply before Tuesday, but I'll check it out asap.

So, if I understood correctly from your initial comment, sorting parameters will be persistent through filtering and sorting other columns, and will be reset by clicking on the sorting icon two or three times in a sequence? I must say it's an interesting idea, is there any reference implementation that works like this? Because I can't remember seeing this kind of behaviour anywhere.

**Comment by Saulis** [comment]
Oh and, for the rotation, could we just rotate the whole paper-icon-button element?

**Comment by userquin** [comment]
Hi Sailus:

The logic to keep sortOrder is not present in iron-data-table, the logic resides in another element wrapping iron-data-table. I need this functionallity so I have done this manually (see filtering.html).

The sequence is clicking three times (on the same column): first time will sort asc (as single sorting), second time will sort desc (as single sorting) and the third click will remove the sorting (instead of sort asc again like single sort does). Once removed sorted column, if there is more than one column sorted, then the same criteria is applied; if only one sorted column, fallback to default sorting (see modified _sort function); in all cases, the sort action will propagate sortOrder object to iron-data-table. This function is not included in the logic, I must find a way to include it (see filtering.html) in iron-data-table.

About this behavior, I usually include a second "button" to remove the sorted column when aria-sorted attribute is present in thead.th. I'm working to include aria-\* in data-table-column-sort and maybe I will try to include a new attribute to allow multi-sort, so the user will not need to include its own logic.

About the rotation: I rotate the paper-icon-button, but the sort-order is included as paper-icon-button:after decorator with its content as attr(sort-order), so all is rotated (also the number, so it will appear rotated/inverted on the left upper corner).

![sort-3](https://cloud.githubusercontent.com/assets/6311119/14066829/3d9acef0-f455-11e5-8e08-74edc0934774.png)

Bye.

**Comment by userquin** [comment]
About the persitence of the filter and the sortOrder: if the user press F5 both, filter and sortOrder, will be lost. I use in my logic an iron-localstorage to prevent lost this data, I only reset currentPage for pagination to 0 first time page is loaded. Maybe this can be also included in iron-data-table.

**Comment by userquin** [comment]
What do you think?: apply transform(-180deg) when paper-icon-button[direction='desc']:after (works with shady and shadow dom)

![sort-4](https://cloud.githubusercontent.com/assets/6311119/14066918/ca076c7a-f457-11e5-8b67-5822359c3c3c.png)

**Comment by Saulis** [comment]
I'd probably would bind the sort-order in a separate element outside paper-icon-button instead of using the :after

**Comment by userquin** [comment]
I have change the behavior and I have included clear sort button. This button also works on single sort. So, multi-sort works like single-sort with multiple columns (asc then desc and so on until click on clear button).

![single-sort](https://cloud.githubusercontent.com/assets/6311119/14067504/3a6ae89e-f466-11e5-99a1-833224bedf9a.png)

![sort-5](https://cloud.githubusercontent.com/assets/6311119/14067503/31df66f0-f466-11e5-8eb7-dbc0da8a0de7.png)

**Comment by userquin** [comment]
My pull request also include aria-sorted and aria-sort attributes to data-table-column-sort when direction changes or remove attributes when clear sort.

**Comment by Saulis** [comment]
I added my own version built on top of your first two commits - I liked more the original sorting behaviour without the clear icon. 

Changed the `sortOrder` property to be an array always, so there is no need to add any custom logic by the user to enable multi-column sorting. 

Didn't add the aria attributes at this point yet, let's do it in a separate patch, I have few questions regarding them which I'd like to discuss with you in the [**chat**](https://gitter.im/Saulis/iron-data-table?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

I'm ready to merge this patch if it's OK with you?

**Comment by userquin** [comment]
ok. 
I have finally done a "plain" version for x-table, just a wrapper for table (extends: table), x-tbody (extends: tbody) and so on, stopping in x-sortable-th (extends: th). So my tables are just html tables with is=x-table attribute and html5 friendly marckup:

``` html
<table is="x-table">
<thead is="x-thead">
<tr>
<th is="x-sortable-th">
Sortable Table Header
</th>
<th>Plain Table Header</th>
</tr>
</thead>
<tbody is="x-tbody">
<template is="dom-repeat" items="[[data]]">
<tr>
<td>[[item.column0]]</td>
<td>[[item.column1]]</td>
</tr>
</template>
</tbody>
</table>
```

Why? WCAG AA problems. Some projects require AA, so I need to be able to configure all aria-\* attributes around the target table: pagination (aria-controls on pagination buttons), status (Page i, showing from N to M of K: aria-describedby on table) and so on.

About multi-sort column, WCAG AA doesn't specify an aria-\* attribute for column ordering (only if the column is sorted and its direction: aria-sorted and aria-sort respectivelly), so I just remove mulit-sort support when WCAG AA is required.

**Comment by userquin** [comment]
Finally, you must review template code, it is extremelly slow on mobile devices. On my Sony Xperia Z4 tablet (Android,3Gb, 64bit processor...), rendering 175 items with 5 columns takes more than 10s!!!. In my Sony Xperia Z3 Compact phone, takes more than 1 minute!!!!!!. 

In fact, on desktop, this sample also freezes the transition of the SPA when entering the page that renders this iron-data-table (just a few hundred miliseconds, but the effect is visible: more than 100ms in render time is slow). You can see it opening chrome developer tools and activating timeline capture: press F5 on any sample page and analize the results.

This is why I can't use any **-data-table implementation, all are based on Templatizer, my projects require mobile support (android, ios, windows...). My x-table just take miliseconds, the template is rendered directly.

**Comment by Saulis** [comment]
I'm actually testing continuously with an iPhone 5S and Surface Pro3 tablet – trying to take mobile devices seriously into account also, unfortunately don't have any Android devices right now.

Haven't bumped into major performance issues before, but after trying with 10-20 columns I can clearly see that there is a problem even on desktop devices. According to Chrome profiler the issue is the node distribution caused by having a `<content>` element injection separately for each cell. 

Looks like I need to redesign the whole element tree structure. See #38
