### ISSUE TITLE
Shadow DOM: selection-enabled with on-selected-item-changed problem

### ISSUE THREAD

**Issue by userquin** [Saulis/iron-data-table#31]
When enabling selection and listen to selected row:
- selection-enabled attribute
- on-selected-item-changed listener

the event is propagated 3 times and only if clicking outside row cell text.

Using shady dom the behavior is correct, only one event and propagate the event when clicking in row cell text, maybe it is an iron-list bug...

Include the script in filtering.html and click on row cell text:

``` html
    <script>
                window.Polymer = window.Polymer || {};
                window.Polymer.dom = 'shadow';
    </script>
  <!-- Using webcomponents-lite.js here to support vaadin-combo-box -->
  <script type="text/javascript" src="../../webcomponentsjs/webcomponents-lite.js"></script>
```

**Comment by userquin** [comment]
iron-list::1388 and polymer:3884 -> cannot find model for div:cell-*

```
    _selectionHandler: function(e) {
      if (this.selectionEnabled) {
        var model = this.modelForElement(e.target);
        if (model) {
          this.toggleSelectionForItem(model[this.as]);
        }
      }
    },

modelForElement: function (el) {
var model;
while (el) {
if (model = el._templateInstance) {
if (model.dataHost != this) {
el = model.dataHost;
} else {
return model;
}
} else {
el = el.parentNode;
}
}
}
```

**Comment by userquin** [comment]
From iron-data-table page:
Cell elements are placed outside the shadow root of the iron-data-table which allows them to be styled by the user.

So when tapping on cell, iron-list cannot find the model, has been moved in the tree: the patch retarget the tap event on the cell to its logical data-table-cell (when creating the div cell, check if shadow dom is present and attach a listener to retarget the event).

**Comment by Saulis** [comment]
Filed an issue to iron-list: https://github.com/PolymerElements/iron-list/issues/222
