### ISSUE TITLE
Filtering with numbers is broken (solution)

### ISSUE THREAD

**Issue by DeadcatDev** [Saulis/iron-data-table#37]
Hi,

when items object holds numbers there is a bug for filtering it on iron-data-table on line 592 which says that "value.toLowerCase() is not bla bla" - because it can do the numeric lowercase so to fix it simply add ".toString()" on line 592 in _filter function :

so i just changed

```
if (value.toLowerCase().indexOf(filter[i].filter.toLowerCase()) === -1) {
    return false;
}
```

to

```
if (value.toString().toLowerCase().indexOf(filter[i].filter.toLowerCase()) === -1) {
    return false;
}
```

OR we can do this between lines 591/592:

```
if(typeof value == "numeric") value = value.toString();
```

Hope i helped a lil bit :)

**Comment by Saulis** [comment]
Thanks!
