### ISSUE TITLE
Filter fails when it hits a null value.

### ISSUE THREAD

**Issue by mwinters-stuff** [Saulis/iron-data-table#46]
With a null value in one of my columns (not intentionally, its in the data source), the filter crashes when it hits it.. in _filter

```
            if (value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
              return false;
            }

```

Fails on the "toString()"

A fix is.

```
            if (!value || value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
              return false;
            }
```

Good work on the table, I like using it better than the simple one I created a while back..

**Comment by Saulis** [comment]
Thanks for the report!

I'll commit a fix asap.

**Comment by Artanis** [comment]
In acb6473, rows with `undefined` or `null` cells being filtered don't come back when you erase the filter string.

The guard against those values doesn't check the filter string to see if it's supposed to be filtering on that column _at all_, and just returns `false` for them.

edit: changed my local copy to this for the time being, though it's probably not the best solution:

``` javascript
if(!filter[i].filter) {
  // don't use an empty filter
  continue;
} else if (!value || value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
  // nothing to test against (fail), or test failed
  return false;
}
```

**Comment by Saulis** [comment]
@Artanis that's a good catch, and the solution LGTM.
