### ISSUE TITLE
styling options are lacking - no way to provide class names to rows or cells

### ISSUE THREAD

**Issue by ktiedt** [Saulis/iron-data-table#47]
The only styling option you have is to pass in an element with the classes you want in the template... this is a very excessive route to styling a row for example based on some value in the row...

It would be nice if there was a row/cell hook that allowed class names to be applied directly to the row/cell elements avoiding the costly overhead of 1 function per cell just to style a row (not to mention the added overhead of wrapper elements to make it happen.

**Comment by Saulis** [comment]
Yeah I think a hook would be a reasonable thing to add. I'll see what I can do.

**Comment by Saulis** [comment]
Please take a look at https://github.com/Saulis/iron-data-table/compare/feature/bind-hook

That adds a hook for each cell data binding call, would that work for you?

**Comment by ktiedt** [comment]
Really need row as well, is it as simple as this?

**Comment by Saulis** [comment]
@ktiedt you should be able to access the row with `cell.parentElement`

**Comment by ktiedt** [comment]
Ok, well, that seems an odd way to add classes to a row, but it works I guess... 

It is odd that you would tell someone 'add a function to a cell to change the row'

**Comment by Saulis** [comment]
Would it be less confusing if I provide the `cell.parentElement` as a function argument `row` ? As in `bindHook(data, cell, row)` – the callback would still be called on each cell though. I'd rather not add two separate callbacks for cells and rows since that would require changing how the internals work quite a bit.

**Comment by ktiedt** [comment]
Aside from the odd aspect of touching cells to modify rows, my major
concern is performance due to a row decorator being in cell callbacks,
unless it can be guaranteed that it will only ever run once per row and not
once per cell per row.

-Karl Tiedt

**Comment by Saulis** [comment]
That's a good point. It's probably a smaller performance hit overall if I add a separate callback for rows even if it wouldn't be in use by everyone.

I'll put it together as soon as I get some time on my hands.

**Comment by Saulis** [comment]
I've uploaded a new branch for [`feature/bind-hook`](https://github.com/Saulis/iron-data-table/compare/feature/bind-hook) which contains separate hooks for cells and rows. Let me know if it works for you.

**Comment by Saulis** [comment]
I've went ahead and merged this version with functions to style both `<data-table-row>` and `<data-table-cell>` separately. Please feel free to reopen this issue in case I got something wrong.
