### ISSUE TITLE
Hiding data-table-colums via a paper-checkbox does not work with shadow dom

### ISSUE THREAD

**Issue by bartolom** [Saulis/iron-data-table#51]
Following the example with https://saulis.github.io/iron-data-table/demo/columns.html the "show/hide" seems only to work with Shady-DOM but not Shadow-DOM

works: `window.Polymer = {lazyRegister: true};`
doesn't work: `window.Polymer = { dom: 'shadow', lazyRegister: true};`

```
<paper-checkbox style="margin: 20px" checked="{{checked}}">more info</paper-checkbox>
...
<data-table-column name="Foo" sort-by="foo" hidden="[[!checked]]">
...
Polymer({
    // ...
    properties: {
      checked: Boolean, 
```

(I use iron-data-table inside a custom element of mine, and not in the main html page with dom-bind, maybe thats a difference.)
Chrome 49, Chrome 50 (Windows 10)

**Comment by Saulis** [comment]
Thanks for the report!

Indeed, `dom-bind` seems to work just fine. Looks like the default global style for `[hidden]` doesn't penerate the Shadow root which caused this issue.
