### ISSUE TITLE
Fast typing on a filter breaks item select

### ISSUE THREAD

**Issue by mwinters-stuff** [Saulis/iron-data-table#54]
When typing at a resonable speed on a filter, selecting those items will start to give the error

elements.html:25147 Uncaught TypeError: <item> should be a valid item

If I type slower this doesn't happen.

A debounce is needed so that the filter is not updated on every key press, the iron-list can not handle the contents being changed so fast..

**Comment by Saulis** [comment]
Hi! Thanks for the report, I actually had a debounce there in an earlier version, but removed it some point after implementing the lazy loading feature. I'll add it back asap.

**Comment by Saulis** [comment]
I've added a `250ms` debounce to branch `fix/filter-debounce`, let me know if it works for you! And if the debounce should be longer or shorter.

**Comment by mwinters-stuff** [comment]
Worked well..

Not sure if it was related, on the same page is 4 lists, the last one to be populated had started to show the same message when I clicked on an item, there is no filter on that list.. That list and one other have their data set right after each other (with this.set) 
I solved it by clearing the data variables before the method that generates the data.. ( i create into a temporary array before setting the data in one go).

**Comment by Saulis** [comment]
Hmm.. sounds a bit peculiar. I can take a look if you can provide a JSBin that reproduces the issue. I made a template for you: http://jsbin.com/yekapo/edit?html,output

**Comment by Saulis** [comment]
I'm going to go ahead with this fix, please reopen this or add new issue if you find out something related with the issue you described.
