### ISSUE TITLE
Sorting messes up with two-way data-binding

### ISSUE THREAD

**Issue by gdavalos** [Saulis/iron-data-table#57]
I recently began using this element and I find it to be pretty awesome but I found a couple of issues while trying to use the built in sort features:
- The first one is a rather simple one I guess, the sort causes an error if the value of that column is undefined on a row.
- The biggest one though is what I mentioned in the title, using the sort feature on a column which is editable with two-way data-binding sometimes generates a weird behavior in which the values of several rows (if not all) end up synchronizing...

That last behavior is somewhat random but to trigger it you should trigger the sort and edit the values of different rows and then repeat those two steps several times (sometimes sorting multiple times before editing).

From what I've observed, this behavior happens no matter what column of the table is sorted as long as one of the columns is editable.

**Comment by Saulis** [comment]
Hi!

Thanks for the report!

Would be awesome if you could reproduce the problems for me in a JSBin: http://jsbin.com/yekapo/edit?html,output

**Comment by gdavalos** [comment]
Here's the [jsbin](http://jsbin.com/yekaqayebo/1/edit?html,output)

If you sort, then edit multiple rows, sort, edit, etc. the behavior will eventually happen.

**Comment by Saulis** [comment]
Yes, I can see it now, so eventually it seems that same item gets bound to multiple rows.

**Comment by gdavalos** [comment]
Yeah, I don't know if they just show the same item or if all the items' values get synchronized but that's what's happening there.

Oh, and I just remembered that the sorting also showed some weird behavior on both Safari and Chrome for iOS, I think it was a similar one in which some rows showed the same value when it should've been different (this happened even on uneditable columns).
