### ISSUE TITLE
Be able to custom data-table-cell style

### ISSUE THREAD

**Issue by maxiplay** [Saulis/iron-data-table#59]

**Comment by maxiplay** [comment]
Flex can create display bugs in certains use case. For example when content become too big with a user action. i would like to be able to customize data-table-cell style with css variable

**Comment by Saulis** [comment]
Hi,

you can override all data-table-cell element styles with a `data-table-cell` CSS selector. If you want to style cells differently depending on content, you can use the new `beforeCellBind` hook.

Please see http://saulis.github.io/iron-data-table/demo/styling.html for examples.

**Comment by maxiplay** [comment]
Ok good. My mistake was to try selector on data-table-column. Thank you

**Comment by Saulis** [comment]
:+1:
