### ISSUE TITLE
dynamically adding elements

### ISSUE THREAD

**Issue by kzahel** [Saulis/iron-data-table#6]
Hi! This looks really promising. I hope I can use it in my project.

I would like to be able to dynamically add elements using this.push, etc. When I do this, it does not display the newly added elements, as it does with iron-list. I may be doing something wrong. Here is what I am trying:

https://gist.github.com/kzahel/5b86054e42a9ecd898fc

**Comment by kzahel** [comment]
Hmm if I add it to the underlying iron-list, it works fine. I guess that seems reasonable enough.

```
       addUser: function(user) {
            this.$$("iron-data-table").$.list.push('items', user)
        }
```

**Comment by Saulis** [comment]
Hi!

Yes, indeed I haven't gotten around adding a proper observer for the `items` property yet. 

Thanks to #7, we'll have that in the next release, which should done by the end of this week at latest.
