### ISSUE TITLE
multiselection does not work in safari, IE and Firefox. Chrome is ok

### ISSUE THREAD

**Issue by jacsbro** [Saulis/iron-data-table#63]
I have a data table with multiselect. It's ok for chrome but not for other browsers. Can be observed as well on the demopage. In my app I see an error in the console - in the demo there is no error, but the row is not being selected either:
`[Error] TypeError: undefined is not an object (evaluating 'Polymer.dom(e).event.path.filter')
    _selectionHandler (data:text/javascript;charset=utf-8,%0A…%0A:255)
    handler (data:text/javascript;charset=utf-8,Pol…%0A:496)
    dispatchEvent
    fire (data:text/javascript;charset=utf-8,Pol…%0A:1252)
    fire (data:text/javascript;charset=utf-8,Pol…%0A:833)
    forward (data:text/javascript;charset=utf-8,Pol…%0A:1123)
    click (data:text/javascript;charset=utf-8,Pol…%0A:1108)
    handleNative (data:text/javascript;charset=utf-8,Pol…%0A:723)`

Seems like on-selected-items-changed is not fired.

Any ideas? Thanks for checking.

**Comment by Saulis** [comment]
Thanks for the report, hadn't noticed it at all. The problem probably relates how `iron-list` detects selections (based on tap event target) – I'll fix this by replacing the selection functionality with my own in the next beta release.

**Comment by jacsbro** [comment]
looking forward to it! Thanks for that great component.
