### ISSUE TITLE
 this.$.container.style.width stay to 0px after hidden attribute is removed

### ISSUE THREAD

**Issue by maxiplay** [Saulis/iron-data-table#64]
When hidden change on parent element, the width does not change.

**Comment by maxiplay** [comment]
I suggest to open the access to resizeCellContainers method in order to manually resize the container. Do you have an better solution ?

**Comment by Saulis** [comment]
Hi!

I'm not 100% sure I understand the use case here... If you want the width to be `0px` can't you just set the `width` instead of using `hidden`?

**Comment by maxiplay** [comment]
My use case is I lazy load differents page (iron-page) and a page contains iron-data-table. When I go to this page the iron-data-table librairy is not again loaded. During loading I apply effect so the page is not again displayed. There is a tiny time during the end-initialisation of iron-data-table and the end-loading event detected. So the iron-datatable is init with no size because it is hidden. I would like to mannually call resize when I detect that loading is finished

**Comment by Saulis** [comment]
Ah.. ok now I get the problem. Right, so have you tried calling `notifyResize()` on the `iron-data-table` element?

It's a function from `IronResizableBehavior` which fires `iron-resize` which in turn runs the `_resizeCellContainers`

**Comment by Saulis** [comment]
@maxiplay any luck?

**Comment by maxiplay** [comment]
I did not had time to try but i trust you ;). Its seems good. I did not know you use IronResizableBehavior. I will recontact you if it does not resolve it.
