### ISSUE TITLE
How to do a Dynamic table

### ISSUE THREAD

**Issue by Stefdv** [Saulis/iron-data-table#65]
using Polymer.
I don't know the structure of my table upfront, so i need to create it dynamicly.
Right now i can make the columns  dynamicly, but then inside the template
`<iron-data-table items="[[recordList]]" >`
`<template is="dom-repeat" items="[[columnList]]" as="column">`
`<data-table-column name="[[column.label]]" >`
`<template>[[item.name.first]]</template>`
`</data-table-column>`
`</template>`
`</iron-data-table>`
How can i 'link' the item to the columnName ? I can't just do 
`<template>[[item[column.labe]l]]</template>`

**Comment by Saulis** [comment]
Hi!

Not sure what you mean by "linking" the item and column together, but you should be able to bind the `column` from `dom-repeat` normally anywhere you like.

So in practice:

``` html
<data-table-column name="[[column.label]]">
  <template>[[column.label]]</template>
</data-table-column>
```

But.. looking at your example I would guess that you're trying to access a property on the `item` with a name of the `column.label` right?

For that, I'd suggest having a function in the parent component which takes both `item` and `column.label` as parameters.

``` js
_itemValue: function(item, prop) {
  return item[prop];
}
```

``` html
<data-table-column name="[[column.label]]">
  <template>[[_itemValue(item, column.label)]]</template>
</data-table-column>
```

**Comment by Stefdv** [comment]
Tx for the reply. 
Yes, that is what i mean...and the solution is so obvious ;) 
tx again ( also for iron-datatable)

**Comment by Saulis** [comment]
np!

**Comment by Stefdv** [comment]
Sorry...haven't had time to actually try it out...

```
  <iron-data-table items="[[records]]">
        <template is="dom-repeat" items="[[origin.fields]]" as="column">
          <data-table-column name="[[column.label]]">
           <template>[[_itemValue(item,column.label)]]</template>

          </data-table-column>
        </template>
    </iron-data-table>
```

```
  _itemValue: function(record,prop) {
        console.log(record,prop)
        return record[prop]
      },
```

now it seems that in `<template>[[_itemValue(item,column.label)]]</template>`  column.label is not accesible anymore. If i only send 'item' to the `_itemValue` function it logs the item. If i only send column (or column.label) it doesn't do anything. 
Note: The columns-names are rendered 

A few hours later...
Nope: column is not available anymore inside the `<data-table-column>`

**Comment by Stefdv** [comment]
Ah...please disregard...i messed up my column.label..
It was MY mistake..sorry about that.
