### ISSUE TITLE
Cannot read property 'item' of undefined. error after porting to new architecture of polymer App Toolbox

### ISSUE THREAD

**Issue by abhinavzspace** [Saulis/iron-data-table#66]
I am running iron-data-table on polymer comfortably.

Recently I was trying to port my code to the newly released [App Toolbox](https://www.polymer-project.org/1.0/toolbox/server) architecture of polymer. I am having a strange problem now.

Getting the following console error on line 781 of iron-data-table.html:
`Cannot read property 'item' of undefined`

I have checked both (my previous code and the new) have the same versions and everything else is same. It must be because of PRPL pattern introduced in this App Toolbox, i.e. lazy loading elements. Because that is the only difference I see. If thats right, what is the right way to do it?

If you need any more info on the problem, let me know.

Thanks!

**Comment by Saulis** [comment]
I remember having some problems in the past when I tried lazily import `<iron-list>` so it might indeed be related to that. I need to look into it and it would be awesome if you could provide a simple example app I could use to try it out.

Thanks!

**Comment by abhinavzspace** [comment]
I have reproduced this issue by creating a sample app by implementing iron-data-table in basic polymer template.

[https://github.com/abhinavzspace/iron-data-table-issue](https://github.com/abhinavzspace/iron-data-table-issue)

I have implemented the iron-data-table element at src/my-view1.html

Instructions are simple. Just run `bower install` and then run `polymer serve`. Then go to `localhost:8080/view1`. You will find the error in console.

Let me know if this helps.

**Comment by Saulis** [comment]
Thanks for the sample app, the issue was pretty simple – I'll release the next beta shortly.

**Comment by abhinavzspace** [comment]
I just checked out the 1.0.0-beta2 version in the same sample app that I made. The iron-data-table is not getting styled properly, but there is no error on console this time.

It works perfectly when I preload the view1.html file.

I don't know. May be I missed something.

**Comment by Saulis** [comment]
If you mean the `default-styles.html`, yeah they don't seem to work. The way how Polymer works (and this is based on my personal understanding by just reading the code) is that it reads the `custom-style` style elements as one of the first steps of the Polymer init phase. And AFAIK, it's done only once. So, loading style elements (custom-styles) later, their mixins and custom properties won't get picked up.

Tried quickly to find some issues/references to back me up on this on the Polymer Github site, but couldn't find anything. That said, if you move the import of `default-styles.html` to your `index.html` everything works.
