### ISSUE TITLE
rowDetails do not work when iron-data-table is being wrapped by parent component

### ISSUE THREAD

**Issue by davitykale-zz** [Saulis/iron-data-table#74]
I have a component that wraps `iron-data-table` and passes in the `data-table-column`s like so:

``` html
<dom-module id="custom-grid">
  <iron-data-table>
    <content select="data-table-column"></content>
  </iron-data-table>
</dom-module>
```

When i try setting row details, however, the click handler for `iron-data-table` is consistently not being able to recognize the row-detail template passed in alongside `data-table-columns` (`this.rowDetails` is always null in line 1086 of `iron-data-table.html` even when I set it myself in the `ready` callback of the wrapper component).

**Comment by Saulis** [comment]
Make sure you've added `<content select="[is=row-detail]"></content>` also to your 'custom-grid' element.

**Comment by davitykale-zz** [comment]
I added that right above the content selector for `data-table-column`, but am still running into the same issues

**Comment by Saulis** [comment]
Can you try if the branch `fix/row-details-content` branch works for you?

**Comment by davitykale-zz** [comment]
I don't think it fixes my issue :/

**Comment by davitykale-zz** [comment]
I spoke too soon! It didn't seem to work with beta2, but this definitely works with beta3!

**Comment by davitykale-zz** [comment]
Ah, I may have spoken too soon yet again haha. When `details-enabled` is set, the `fix/row-details-content` branch works perfectly. However, for the second example on the demo page, where `details-enabled` is not set but there's a `paper-checkbox` set to toggle the `expanded`property, does not work.

**Comment by Saulis** [comment]
You're right, nice catch! I'll see what's wrong with that.

Update: looks like there has been a bug with this for a some time – `selected` and `expanded` template variables don't seem to be bound to the correct template context although they should. Works fine with `dom-bind` though

**Comment by Saulis** [comment]
@davitykale please try the branch again, I think I got it fixed.

**Comment by davitykale-zz** [comment]
I'm still unable to trigger the row details through the `expanded` property if `detailsEnabled` is not set :/

**Comment by Saulis** [comment]
Which browser are you using? Does http://plnkr.co/edit/AIsQJ8eeAJ58pV6Dwog7?p=preview work for you?

Update: I just realised you must be injecting the `<data-table-column>` elements also from the parent component, right? That's what I was missing.

**Comment by Saulis** [comment]
@davitykale OK, I've updated the branch and the plnkr, should work better?

**Comment by davitykale-zz** [comment]
Yes! It absolutely works! Thank you so much, @Saulis! I super appreciate this!
