### ISSUE TITLE
filterBy and sortBy are broken in 1.0.0.beta2

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#76]
In fact, `filter-by` and `sort-by` attributes work nicely in 1.0.0-beta1, but in beta2 they don't.
We have spent more than hour while trying to detect the reason, but with no success.
Please check it and also update demos to use the latest version.

**Comment by thepill** [comment]
+1 confirm

**Comment by Saulis** [comment]
This is a definite regression, thanks for reporting. I'll release a fix asap.

**Comment by Saulis** [comment]
Please try if branch `fix/column-binding` works for you. If OK, I'll release it as `beta3`

**Comment by thepill** [comment]
Seems to be working under chrome.
But now issue #75 appears under IE 11

**Comment by Saulis** [comment]
@thepill yeah I'm getting `Expected ':'` in IE11 but having a real hard time pinpointing the reason because it doesn't give me a line number...

**Comment by Saulis** [comment]
Found it, was missing `function` keyword in one of the functions. Force pushed a new version to the branch.

**Comment by thepill** [comment]
fixed! 
Another thing: the clear button inside the filter input is missing within chrome - is working in IE

**Comment by Saulis** [comment]
Great!

You're probably looking at the native clear icon which IE and Edge puts on every input field by default. There's a CSS pseudo selector to hide it but can't be applied to paper-input because unless you use deep selectors.

**Comment by thepill** [comment]
dont want to hide it, i like it 👍 
Thanks for your work!
