### ISSUE TITLE
Switching Polymer to "dom: shadow" breaks row expanding

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#80]
When using `shady` mode, problem is not reproduced. It only happens when switching to `shadow`.

```
iron-data-table.html:781 Uncaught TypeError: Cannot read property 'item' of undefined
```

This is the next code:

```
      _itemCollapsed: function(e) {
        var item = e.detail.item || e.model.item;
...
```

I found out that it happens on first call of the listener, and at this moment `e.model` is undefined for some reasons. Looks like a too early listener call bug.

**Comment by Saulis** [comment]
Hmm, seems to be working here: http://jsbin.com/kefajad/edit?html,output

Are you able to some changes that would reproduce the problem there?

**Comment by web-padawan** [comment]
Sorry, it's my fault. Occasionally used `beta1` while testing that. All is OK with `beta3`.
