### ISSUE TITLE
individual row selection not working in non chrome browsers

### ISSUE THREAD

**Issue by sowsan** [Saulis/iron-data-table#82]
hello -

If we have multiselection enabled and if we try to select individual check boxes its not working. Issue is reproducing in firefox and edge latest browser versions. In chrome its working. I have tested it with the demo bower_components/iron-data-table/demo/index.html

Thanks for your help !

**Comment by Saulis** [comment]
Hi! Are you using the latest beta?

**Comment by sowsan** [comment]
Thanks Sauli. I'm using  "iron-data-table": "1.0.0-beta3",, hope that is the latest.

**Comment by Saulis** [comment]
Can you modify this example app to reproduce the problem on Firefox: 
http://jsbin.com/hekuwe/edit?html,console,output

**Comment by sowsan** [comment]
THanks. I will try it out and let u know.

**Comment by Saulis** [comment]
@sowsan any luck?

**Comment by sowsan** [comment]
Thanks for your follow-up. Yes, the link that you have given just works fine. When I tested the demo in the bower component with the latest version it looks works fine in firefox and edge. I will integrate it in my app and will see if it works as expected. Thanks again !
