### ISSUE TITLE
First row doesn't expand when iron-data-table is inside a parent component

### ISSUE THREAD

**Issue by Saulis** [Saulis/iron-data-table#88]

**Comment by Saulis** [comment]
`Polymer.dom(e).localTarget` seems to be returning always the row element on the first row.
Related with #89

**Comment by Artanis** [comment]
Is this what I'm seeing here, or is this different?

http://jsbin.com/fijicec/edit?html,output

**Comment by Saulis** [comment]
@Artanis yes I think so, changing the branch to `rewrite-templatizers` seems to fix the issue.

**Comment by Artanis** [comment]
I just pulled the update into my project, and it does indeed fix the issue.
