### ISSUE TITLE
Filtering broken when injecting columns from a parent node

### ISSUE THREAD

**Issue by Saulis** [Saulis/iron-data-table#90]
``` html
<!doctype html>
<head>
<meta name="description" content="iron-data-table beta3">
  <meta charset="utf-8">
  <script src="../../webcomponentsjs/webcomponents-lite.min.js"></script>
  <link href="../iron-data-table.html" rel="import">
  <link href="../default-styles.html" rel="import">
</head>
<body>
  <dom-module id="x-foo">
    <template>
      <iron-data-table items="[[items]]">
        <content select="data-table-column"></content>
      </iron-data-table>
    </template>
    <script>
      document.addEventListener('WebComponentsReady', function() {
        Polymer({
          is: 'x-foo',
          properties: {
            items: {
              value: function() {
                var items = [];

                for (var i=0; i < 100; i++) {
                  items.push({'value': 'foo'+i});
                }

                return items;
              }
            }
          }
        });
      });
    </script>
  <dom-module>

  <x-foo>
    <data-table-column name="Column 1" filter-by="value">
      <template>[[item.value]]</template>
    </data-table-column>
  </x-foo>
</body>

```

**Comment by Saulis** [comment]
Related with https://github.com/Polymer/polymer/issues/3196

**Comment by tpluscode** [comment]
Hi. You mentioned Polymer/polymer#3196. Did you somehow overcome the problem in issue #93?

**Comment by Saulis** [comment]
@tpluscode IIRC the problem was running `templatize()` with two different templates on the same `Templatizer` object. Some variables inside it don't get reset after templatizing again and then template instances are expected to have some instance properties that the previous template was having.

Worked around the issue by making sure there is always a single template used per Templatizer.

**Comment by tpluscode** [comment]
Sadly, I don't think that's my problem. Even with one template I can't get it to work.

And by the way, what do you mean single template per templatizer? It's a behavior so I guess one template per element instance?

**Comment by Saulis** [comment]
Yeah exactly, per element instance. 

I have a faint recollection that I might've done also a monkey patch somewhere... Let's see.

Update: found it https://github.com/Saulis/iron-data-table/blob/master/data-table-templatizer-behavior.html#L90
