### ISSUE TITLE
column not available for binding in row cell templates

### ISSUE THREAD

**Issue by Stefdv** [Saulis/iron-data-table#92]
I would like to reopen "How to do a Dynamic table #65"

```
 <iron-data-table items="[[records]]">
     <template is="dom-repeat" items="[[origin.fields]]" as="column">
        <data-table-column name="[[column.label]]">
          <template>[[_itemValue(item,column.labe)]]</template>
        </data-table-column>
     </template>
  </iron-data-table>
```

```
 _itemValue: function(item,column) {
        return item[column)
      },
```

inside `<data-table-column name="[[column.label]]">` the column.label is not accesible. The name does appear in the header, but i can not acces it to create my itemvalue

**Comment by Saulis** [comment]
Hi!

It's actually because `column` has not been bound to row cell templates (it never has).  Could you please try branch `rewrite-templatizers` if it works better for you?

**Comment by Saulis** [comment]
Oh right, and `column` inside the cell template is reserved for the actual column element instance. So you need to use some other variable name if you want reference the items from the `dom-repeat`

**Comment by Saulis** [comment]
More precisely: 

``` html
<iron-data-table items="[[records]]">
     <template is="dom-repeat" items="[[origin.fields]]" as="col">
        <data-table-column name="[[col.label]]">
          <template>[[_itemValue(item,col.label)]]</template>
        </data-table-column>
     </template>
  </iron-data-table>
```

OR (supported in `rewrite-templatizers`) 

``` html
<iron-data-table items="[[records]]">
     <template is="dom-repeat" items="[[origin.fields]]" as="col">
        <data-table-column name="[[col.label]]">
          <template>[[_itemValue(item,column.name)]]</template>
        </data-table-column>
     </template>
</iron-data-table>
```

**Comment by Stefdv** [comment]
Perfect:) I used the Master branch with your first example...It's working now. Tx for your support.

**Comment by Stefdv** [comment]
FYI, using the branch `rewrite-templatizers`  i get an error saying that "compute method _itemValue is not defined"

**Comment by Stefdv** [comment]
**BRANCH `rewrite-templatizers`  !!!**

It seems that the reference to the parent element is lost. None of the functions works

```
 <template is="dom-repeat" items="[[origin.fields]]" as="col">
      <data-table-column name="[[col.label]]" sort-by="[[col.label]]" filter-by="[[col.label]]">
        <template>
          <template is="dom-if" if="{{_checkString(col)}}">
           [[_itemValue(item,col.label)]]
          </template>
         <template is="dom-if" if="{{_checkBoolean(col)}}">
           <paper-checkbox checked="{{_checkBooleanState(item,col.label)}}" on-change="_checkBoxChanged" name="[[col.label]]" disabled></paper-checkbox>
          </template>
        </template>
      </data-table-column>

     </template>
```

**Comment by Saulis** [comment]
Yes, I see the problem, thanks for reporting. 

I've pushed a new commit to the same branch, please see if it helps.
