### ISSUE TITLE
Do not import all of the iron-icons

### ISSUE THREAD

**Issue by web-padawan** [Saulis/iron-data-table#97]
Actually `datatable-column-sort` imports all of the `iron-icons.html`
This is not a good idea, as datatable only uses a few icons.

I suggest creating a custom iconset [like this](https://github.com/David-Mulder/paper-datatable/blob/master/datatable-icons.html) instead of importing the whole `iron-icons` bundle.

**Comment by Saulis** [comment]
Good idea! Would you mind helping me out making it happen?

**Comment by web-padawan** [comment]
Sure! Will create a PR to implement that soon.
