### ISSUE TITLE
Issue with testing a component that wraps iron-data-table when writing tests

### ISSUE THREAD

**Issue by davitykale-zz** [Saulis/iron-data-table#99]
I am using web-component-tester to test a component that wraps iron-data-table. Whenever I run the test suites, however, I run into the following error:

`Error: Cannot read property '_rootDataHost' of undefined
                 data-table-column.value at ../iron-data-table/data-table-column.html:302`

**Comment by Saulis** [comment]
Can you try out if latest `master` works any better? The error msg should be gone but not 100% if the template is available.

**Comment by davitykale-zz** [comment]
I still get the error :/. I believe the error has to do with collumn.dataHost being undefined in the value function of template. Not sure if that helps at all

**Comment by Saulis** [comment]
OK, I was able to reproduce the issue with this:

``` html
<test-fixture id="grid">
    <template>
      <x-foo>
        <data-table-column name="First">
          <template>[[item.col1]]</template>
        </data-table-column>
        <data-table-column name="Second">
          <template>[[item.col2]]</template>
        </data-table-column>
      </x-foo>
    </template>
  </test-fixture>

  <dom-module id="x-foo">
    <template>
      <iron-data-table>
        <content select="data-table-column"></content>
      </iron-data-table>
    </template>
    <script>
      Polymer({
        is: 'x-foo'
      });
    </script>
  </dom-module>
```

My first impression is that `<test-fixture>` doesn't properly set the `dataHost` for the template instance it creates – as if it doesn't have a data context at all. This requires more investigation...

As a workaround, you can wrap `<x-foo>` in a `dom-bind` or `dom-if` e.g.:

``` html
  <test-fixture id="grid">
    <template>
      <template is="dom-bind">
        <x-foo>
          <data-table-column name="First">
            <template>[[item.col1]]</template>
          </data-table-column>
          <data-table-column name="Second">
            <template>[[item.col2]]</template>
          </data-table-column>
        </x-foo>
      </template>
    </template>
  </test-fixture>
```

**Comment by Saulis** [comment]
Should work with `master` now
